services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    command: ["mongod", "--bind_ip_all", "--replSet", "${MONGO_REPLICA_SET}", "--auth", "--keyFile", "${MONGO_KEYFILE_PATH}"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data1:/data/db
      - ./mongodb.key:${MONGO_KEYFILE_PATH}
    networks:
      - mongo-net

  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    command: ["mongod", "--bind_ip_all", "--replSet", "${MONGO_REPLICA_SET}", "--auth", "--keyFile", "${MONGO_KEYFILE_PATH}"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data2:/data/db
      - ./mongodb.key:${MONGO_KEYFILE_PATH}
    networks:
      - mongo-net

  mongodb3:
    image: mongo:latest
    container_name: mongodb3
    command: ["mongod", "--bind_ip_all", "--replSet", "${MONGO_REPLICA_SET}", "--auth", "--keyFile", "${MONGO_KEYFILE_PATH}"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data3:/data/db
      - ./mongodb.key:${MONGO_KEYFILE_PATH}
    networks:
      - mongo-net

  mongodb4:
    image: mongo:latest
    container_name: mongodb4
    command: ["mongod", "--bind_ip_all", "--replSet", "${MONGO_REPLICA_SET}", "--auth", "--keyFile", "${MONGO_KEYFILE_PATH}"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data4:/data/db
      - ./mongodb.key:${MONGO_KEYFILE_PATH}
    networks:
      - mongo-net

  mongo-arbiter:
    image: mongo:latest
    container_name: mongo-arbiter
    command: ["mongod", "--bind_ip_all", "--replSet", "${MONGO_REPLICA_SET}", "--port", "${MONGO_ARBITER_PORT}", "--auth", "--keyFile", "${MONGO_KEYFILE_PATH}"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb.key:${MONGO_KEYFILE_PATH}
    networks:
      - mongo-net

  mongo-init:
    image: mongo:latest
    container_name: mongo-init
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
      - mongodb4
      - mongo-arbiter
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_REPLICA_SET: ${MONGO_REPLICA_SET}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_ARBITER_PORT: ${MONGO_ARBITER_PORT}
      MONGO_TIMEOUT: ${MONGO_TIMEOUT}
    volumes:
      - ./mongo_rs_init.sh:/scripts/mongo_rs_init.sh
    entrypoint: ["/scripts/mongo_rs_init.sh"]
    networks:
      - mongo-net

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports: 
      - "27018:27018" # read
      - "27019:27019" # write
      - "8404:8404"   # stats
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - mongodb2
      - mongodb3
      - mongodb4
    networks:
      - mongo-net
    
  go-app:
    build: ./pipe
    container_name: go-app
    depends_on:
      - haproxy
    networks:
      - mongo-net


volumes:
  mongo-data1:
  mongo-data2:
  mongo-data3:
  mongo-data4:


networks:
  mongo-net:
    driver: bridge
