apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  mongo_rs_init.sh: |
    #!/bin/bash
    set -e

    HOSTS=(
      "mongo-statefulset-0.mongo-headless-service"
      "mongo-statefulset-1.mongo-headless-service"
      "mongo-statefulset-2.mongo-headless-service"
      "mongo-statefulset-3.mongo-headless-service"
      "mongo-statefulset-4.mongo-headless-service"
    )

    PORT=27017
    ARBITER_PORT=27018

    USER="${MONGO_INITDB_ROOT_USERNAME}"
    PASS="${MONGO_INITDB_ROOT_PASSWORD}"
    RS_NAME="rs0"

    echo "Waiting for MongoDB nodes to respond..."

    for host in "${HOSTS[@]}"; do
        if [[ "$host" == "${HOSTS[4]}" ]]; then
            port=$ARBITER_PORT
        else
            port=$PORT
        fi

        until mongosh --host "$host" --port "$port" --quiet \
            --eval "db.runCommand({ ping: 1 }).ok" &>/dev/null; do
            echo -n "."
            sleep 1
        done

        echo " $host ready"
    done

    echo "Initializing ReplicaSet..."

    CONFIG=$(cat <<EOF
    {
      "_id": "$RS_NAME",
      "members": [
        { "_id": 0, "host": "${HOSTS[0]}:${PORT}", "priority": 2 },
        { "_id": 1, "host": "${HOSTS[1]}:${PORT}", "priority": 1 },
        { "_id": 2, "host": "${HOSTS[2]}:${PORT}", "priority": 1 },
        { "_id": 3, "host": "${HOSTS[3]}:${PORT}", "priority": 1 },
        { "_id": 4, "host": "${HOSTS[4]}:${ARBITER_PORT}", "arbiterOnly": true }
      ]
    }
    EOF
    )


    mongosh --host "${HOSTS[0]}" --port ${PORT} <<EOF
    try {
        rs.initiate($CONFIG)
    } catch (e) {
        if (e.codeName === "AlreadyInitialized") {
            rs.reconfig($CONFIG, { force: true })
        } else {
            throw e
        }
    }
    EOF

    echo "Waiting for PRIMARY election..."

    while true; do
        state=$(mongosh --host "${HOSTS[0]}" --port ${PORT} --quiet --eval "db.hello().isWritablePrimary")
        if [[ "$state" == "true" ]]; then
            echo "PRIMARY is ready"
            break
        fi
        sleep 1
    done

    echo "Creating root user..."

    mongosh --host "${HOSTS[0]}" --port ${PORT} <<EOF
    use admin
    db.createUser({
      user: "$USER",
      pwd: "$PASS",
      roles: [ { role: "root", db: "admin" } ]
    })
    EOF

    echo "ReplicaSet initialized and root user created successfully."
