apiVersion: v1
kind: Service
metadata:
  name: mongo-external-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mongo-pod
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      nodePort: 30017
