apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  serviceName: mongo-headless-service
  replicas: 5
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo-pod
    spec:
      containers:
        - name: mongod
          image: mongo:latest
          command:
            - sh
            - -c
            - |
              if [ "$(hostname)" = "mongo-statefulset-4" ]; then
                exec mongod --bind_ip_all --replSet rs0 --port 27018
              else
                exec mongod --bind_ip_all --replSet rs0 --port 27017
              fi
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
        labels:
          app.kubernetes.io/name: mongo-pod
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 400Mi
